### ISSUE TITLE
Encoding error when installing on debian

### ISSUE THREAD

**Issue by bustawin** [brandonxiang/geojson-python-utils#1]
Installing this package in debian produces an encoding error, in concrete when _pip_ executes the package's _setup.py_. The `open()` method in debian by default encodes in _ascii_ and it cannot interpret the asian characters in the README.md.

The solution is just changing in the setup.py's `long_description = open('README.md').read()` per `long_description = open('README.md', encoding="utf-8").read()`

Note that in other OS, like Mac, the `open()` method encodes in utf-8 by default.

**Comment by brandonxiang** [comment]
It is no problem of installation in Mac.

I will try to fix it soon. thanx

**Comment by brandonxiang** [comment]
I have fixed it. Check it out
